name: tfsec-pr-commenter
on:
  push:
    
jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          tfsec_formats: sarif
          tfsec_args: --soft-fail --minimum-severity HIGH
          github_token: ${{ github.token }}